### ISSUE TITLE
Love it, would love to run it too!

### ISSUE THREAD

**Issue by Fastidious** [ruairidhflint/days-left#1]
I would love to run my own version of this. I can see where I can edit for my own data, but how to get this running on my own server? Does it require NodeJS, or it simply renders a static page? What would the steps be to run it? TIA!

**Comment by ruairidhflint** [comment]
Hey - thanks!

It shouldn't require much though you will need NodeJS + NPM installed to run the dependencies. 

If you have those installed, you can clone the repository and then run `npm install` in the root directory and then `npm run dev` to get it up and running locally. 

From there I deployed it to Netlify which has a pretty simple deployment process!

**Comment by Fastidious** [comment]
Thank you!
